<a href="https://colab.research.google.com/github/MunSu2001/SKN25-2nd-4Team/blob/main/2026_03_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
from nlp import list_datasets
datasets_list = list_datasets()
print(', '.join(dataset.id for dataset in datasets_list))

TuringEnterprises/Open-RL, nohurry/Opus-4.6-Reasoning-3000x-filtered, crownelius/Opus-4.6-Reasoning-3300x, LeeXiangNO1/DyNativeGaussian_sequence, BytedTsinghua-SIA/CUDA-Agent-Ops-6K, AudioVisual-Caption/ASID-1M, togethercomputer/CoderForge-Preview, peteromallet/dataclaw-peteromallet, nvidia/Nemotron-Terminal-Corpus, google/WaxalNLP, nvidia/Nemotron-ClimbMix, nebius/SWE-rebench-V2, AweAI-Team/Scale-SWE, TeichAI/claude-4.5-opus-high-reasoning-250x, HuggingFaceFW/finephrase, Roman1111111/gemini-3-pro-10000x-hard-high-reasoning, OmniLottie/MMLottie-2M, ronantakizawa/webui, ronantakizawa/github-top-code, FINAL-Bench/ALL-Bench-Leaderboard, nvidia/Nemotron-Research-GooseReason-0.7M, Roman1111111/gemini-3.1-pro-hard-high-reasoning, Anthropic/EconomicIndex, HuggingFaceFW/fineweb-edu, nebius/SWE-rebench-V2-PRs, TianHongZXY/CHIMERA, Jackrong/Qwen3.5-reasoning-700x, HuggingFaceFW/fineweb, OmniLottie/MMLottieBench, skylenage/DeepVision-103K, ScaleAI/SWE-Atlas-QnA, AweAI-Team/Scale-SWE-Distilled, ro

In [ ]:
from transformers import BertModel, BertTokenizer
import torch

In [ ]:
model = BertModel.from_pretrained("bert-base-uncased")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [ ]:
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

In [ ]:
token = tokenizer.tokenize("today is monday")

In [ ]:
tokens = ['[CLS]'] + token + ['[SEP]']
tokens = tokens + ['[PAD]'] + ['[PAD]']
attention_mask = [1 if i != '[PAD]' else 0  for i in tokens ]

In [ ]:
attention_mask

[1, 1, 1, 1, 1, 0, 0]

In [ ]:
torch

<module 'torch' from '/usr/local/lib/python3.12/dist-packages/torch/__init__.py'>

In [ ]:
[tokenizer.convert_tokens_to_ids(x) for x in tokens]

[101, 2651, 2003, 6928, 102, 0, 0]

In [ ]:
tokens = ['[CLS]'] + token + ['[SEP]']
tokens = tokens + ['[PAD]'] + ['[PAD]']
attention_mask = [1 if i != '[PAD]' else 0  for i in tokens ]

In [ ]:
[tokenizer.convert_tokens_to_ids(x) for x in tokens]

[101, 2651, 2003, 6928, 102, 0, 0]

In [ ]:
token_ids = tokenizer.convert_tokens_to_ids(tokens)

In [ ]:
token_ids

[101, 2651, 2003, 6928, 102, 0, 0]

In [ ]:
token_ids = torch.tensor(token_ids).to('cuda')
attention_mask = torch.tensor(attention_mask).to('cuda')

In [ ]:
model = model.to('cuda')

In [ ]:
token_ids = token_ids.unsqueeze(0)
attention_mask = attention_mask.unsqueeze(0)

In [ ]:
hidden_rep, cls_head = model(token_ids, attention_mask=attention_mask)

In [ ]:
outputs =model(token_ids, attention_mask=attention_mask)

In [ ]:
outputs.last_hidden_state[0]

tensor([[ 0.0197,  0.2196,  0.0938,  ..., -0.1899,  0.4116,  0.2325],
        [-0.5819, -0.1249,  0.3125,  ..., -0.2005,  0.9950, -0.6527],
        [-0.9762, -0.2775,  0.4668,  ..., -0.1024,  0.5229,  0.6063],
        ...,
        [ 0.5964,  0.2489, -0.1335,  ...,  0.0682, -0.4352, -0.2907],
        [-0.1634,  0.0760,  0.3225,  ...,  0.1563,  0.4583,  0.2637],
        [-0.1767, -0.0107,  0.2926,  ...,  0.2592,  0.4495,  0.1880]],
       device='cuda:0', grad_fn=<SelectBackward0>)

In [ ]:
from transformers import BertTokenizer, BertForMaskedLM, BertForSequenceClassification

In [ ]:
model = BertForMaskedLM.from_pretrained('bert-base-uncased')

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

BertForMaskedLM LOAD REPORT from: bert-base-uncased
Key                         | Status     |  | 
----------------------------+------------+--+-
bert.pooler.dense.bias      | UNEXPECTED |  | 
bert.pooler.dense.weight    | UNEXPECTED |  | 
cls.seq_relationship.bias   | UNEXPECTED |  | 
cls.seq_relationship.weight | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [ ]:
text = "The capital of France is [MASK]."

In [ ]:
inputs = tokenizer(text, return_tensors="pt")
inputs = inputs.to('cuda')
model = model.to('cuda')

In [ ]:
inputs

{'input_ids': tensor([[ 101, 1996, 3007, 1997, 2605, 2003,  103, 1012,  102]],
       device='cuda:0'), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0]], device='cuda:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]], device='cuda:0')}

In [ ]:
with torch.no_grad():
    outputs = model(**inputs)
    predcitions  = outputs.logits

In [ ]:
mask_token_index = torch.where(inputs["input_ids"] == tokenizer.mask_token_id)[1]

In [ ]:
inputs['input_ids']

tensor([[ 101, 1996, 3007, 1997, 2605, 2003,  103, 1012,  102]],
       device='cuda:0')

In [ ]:
mask_token_index

tensor([6], device='cuda:0')

In [ ]:
predicted_token_id = predcitions[0, mask_token_index].argmax(dim=-1)

In [ ]:
predcitions[0, mask_token_index].shape

torch.Size([1, 30522])

In [ ]:
predicted_token_id

tensor([3000], device='cuda:0')

In [ ]:
predicted_word = tokenizer.decode(predicted_token_id)

In [ ]:
predicted_word

'paris'

In [ ]:
values , indices = torch.topk(predcitions[0, mask_token_index], k=10, dim=-1)

In [ ]:
text = ""
for x in indices:
    text += tokenizer.decode(x)

In [ ]:
words = "The capital of France is {}."
for x in text.split():
    print(words.format(x))

The capital of France is paris.
The capital of France is lille.
The capital of France is lyon.
The capital of France is marseille.
The capital of France is tours.
The capital of France is toulouse.
The capital of France is orleans.
The capital of France is nantes.
The capital of France is brest.
The capital of France is bordeaux.


In [ ]:
kmodel = BertForMaskedLM.from_pretrained('bert-base-multilingual-cased')
ktokenizer = BertTokenizer.from_pretrained("bert-base-multilingual-cased")

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

BertForMaskedLM LOAD REPORT from: bert-base-multilingual-cased
Key                         | Status     |  | 
----------------------------+------------+--+-
bert.pooler.dense.bias      | UNEXPECTED |  | 
bert.pooler.dense.weight    | UNEXPECTED |  | 
cls.seq_relationship.bias   | UNEXPECTED |  | 
cls.seq_relationship.weight | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [ ]:
text  = "거먼은 해당 제품이 2026년 [MASK] 출시될 가능성이 크다고 내다봤다."

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForMaskedLM
import torch.nn.functional as F

model_name = "klue/bert-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForMaskedLM.from_pretrained(model_name)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

BertForMaskedLM LOAD REPORT from: klue/bert-base
Key                          | Status     |  | 
-----------------------------+------------+--+-
bert.pooler.dense.bias       | UNEXPECTED |  | 
bert.pooler.dense.weight     | UNEXPECTED |  | 
cls.seq_relationship.bias    | UNEXPECTED |  | 
cls.seq_relationship.weight  | UNEXPECTED |  | 
bert.embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


BertForMaskedLM(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(32000, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_a

In [ ]:
inputs = tokenizer(text, return_tensors="pt").to(device)
mask_token_index = torch.where(inputs["input_ids"] == tokenizer.mask_token_id)[1]


In [ ]:
print(text)
print(mask_token_index)

거먼은 해당 제품이 2026년 [MASK] 출시될 가능성이 크다고 내다봤다.
tensor([10], device='cuda:0')


In [ ]:
model.eval()
with torch.no_grad():
    outputs = model(**inputs)
    predictions = outputs.logits

In [ ]:
mask_logits = predictions[0, mask_token_index]
probs = F.softmax(mask_logits, dim=-1)

In [ ]:
print(probs.sum())
print(probs.shape)

tensor(1.0000, device='cuda:0')
torch.Size([1, 32000])


In [ ]:
top_values, top_indices = torch.topk(probs, k=10, dim=-1)

In [ ]:
for i in range(10):
    token_id = top_indices[0, i].item()
    token_prob = top_values[0, i].item()
    token_text = tokenizer.decode([token_id])

    rank = i + 1
    print(f"{rank}순위: {token_text} (ID: {token_id}, 확률: {token_prob:.4f})")


1순위: ##에 (ID: 2170, 확률: 0.4437)
2순위: 이후 (ID: 3719, 확률: 0.2417)
3순위: ##쯤 (ID: 3353, 확률: 0.0399)
4순위: 말 (ID: 1041, 확률: 0.0216)
5순위: 중 (ID: 1570, 확률: 0.0215)
6순위: 첫 (ID: 1656, 확률: 0.0180)
7순위: 초 (ID: 1663, 확률: 0.0157)
8순위: ##부터 (ID: 3797, 확률: 0.0150)
9순위: ##께 (ID: 2678, 확률: 0.0127)
10순위: 경 (ID: 591, 확률: 0.0125)


In [ ]:
def predict(text, k=10):
    inputs = tokenizer(text, return_tensors="pt").to(device)
    mask_token_index = torch.where(inputs["input_ids"] == tokenizer.mask_token_id)[1]

    model.eval()
    with torch.no_grad():
        outputs = model(**inputs)
        predictions = outputs.logits


    mask_logits = predictions[0, mask_token_index]
    probs = F.softmax(mask_logits, dim=-1)


    print(probs.sum())
    print(probs.shape)

    top_values, top_indices = torch.topk(probs, k=k, dim=-1)
    return top_values, top_indices


In [ ]:
text = "저는 새로운 환경에서 항상 [MASK] 도전해왔습니다."
top_values, top_indices = predict(text)


tensor(1., device='cuda:0')
torch.Size([1, 32000])


In [ ]:
print(text)
for i in range(10):
    token_id = top_indices[0, i].item()
    token_prob = top_values[0, i].item()
    token_text = tokenizer.decode([token_id])

    rank = i + 1
    print(f"{rank}순위: {token_text} (ID: {token_id}, 확률: {token_prob:.4f})")

저는 새로운 환경에서 항상 [MASK] 도전해왔습니다.
1순위: 끊임없이 (ID: 6542, 확률: 0.1753)
2순위: 열심히 (ID: 5021, 확률: 0.1538)
3순위: 새로운 (ID: 3824, 확률: 0.1070)
4순위: 다시 (ID: 3690, 확률: 0.0880)
5순위: 꾸준히 (ID: 5619, 확률: 0.0490)
6순위: 계속 (ID: 3851, 확률: 0.0347)
7순위: 항상 (ID: 4744, 확률: 0.0293)
8순위: 함께 (ID: 3655, 확률: 0.0285)
9순위: 이렇게 (ID: 3737, 확률: 0.0218)
10순위: 스스로 (ID: 4201, 확률: 0.0195)


In [ ]:
text = """
저는 새로운 [MASK]에서 늘 적극적으로 도전해왔습니다.
초등학교 시절 첫 [MASK]에 적응했던 과정, 고교 시절 체육을 어려워하면서도 끝내 반대항 배드민턴 대회에서
우승한 경험은 저에게 “어떤 상황에서도 최선을 다하면 해낼 수 있다”는 믿음을 주었습니다.
낯선 분야에서도 굴하지 않고 성과를 낸 경험은 이 믿음에 더욱 확신을 주었습니다.
익숙치 않은 전문지식을 습득하고자 [MASK] 정리했습니다.
복잡한 용어들을 공부하며 [MASK] 임한 결과, 직접 PI를 작성하고 거래처와 소통할 수 있는 기회를 얻었습니다."""


In [ ]:
top_values, top_indices = predict(text)
print(text)
for i in range(10):
    token_id = top_indices[2, i].item()
    token_prob = top_values[2, i].item()
    token_text = tokenizer.decode([token_id])

    rank = i + 1
    print(f"{rank}순위: {token_text} (ID: {token_id}, 확률: {token_prob:.4f})")


tensor(4., device='cuda:0')
torch.Size([4, 32000])

저는 새로운 [MASK]에서 늘 적극적으로 도전해왔습니다. 
초등학교 시절 첫 [MASK]에 적응했던 과정, 고교 시절 체육을 어려워하면서도 끝내 반대항 배드민턴 대회에서 
우승한 경험은 저에게 “어떤 상황에서도 최선을 다하면 해낼 수 있다”는 믿음을 주었습니다.
낯선 분야에서도 굴하지 않고 성과를 낸 경험은 이 믿음에 더욱 확신을 주었습니다. 
익숙치 않은 전문지식을 습득하고자 [MASK] 정리했습니다. 
복잡한 용어들을 공부하며 [MASK] 임한 결과, 직접 PI를 작성하고 거래처와 소통할 수 있는 기회를 얻었습니다.
1순위: 스스로 (ID: 4201, 확률: 0.1544)
2순위: 열심히 (ID: 5021, 확률: 0.1292)
3순위: 이를 (ID: 8345, 확률: 0.1000)
4순위: 꾸준히 (ID: 5619, 확률: 0.0745)
5순위: 끊임없이 (ID: 6542, 확률: 0.0698)
6순위: 과감히 (ID: 14385, 확률: 0.0300)
7순위: 꼼꼼히 (ID: 10422, 확률: 0.0272)
8순위: 틈틈이 (ID: 18719, 확률: 0.0261)
9순위: 다시 (ID: 3690, 확률: 0.0243)
10순위: 철저히 (ID: 7365, 확률: 0.0160)


In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [ ]:
model_name

'klue/bert-base'

In [ ]:
model_name = "klue/roberta-large"
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = model.to('cuda')

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: klue/roberta-large
Key                             | Status     | 
--------------------------------+------------+-
lm_head.layer_norm.weight       | UNEXPECTED | 
lm_head.bias                    | UNEXPECTED | 
lm_head.layer_norm.bias         | UNEXPECTED | 
lm_head.dense.bias              | UNEXPECTED | 
roberta.embeddings.position_ids | UNEXPECTED | 
lm_head.dense.weight            | UNEXPECTED | 
classifier.dense.bias           | MISSING    | 
classifier.dense.weight         | MISSING    | 
classifier.out_proj.bias        | MISSING    | 
classifier.out_proj.weight      | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


In [ ]:
text = "냅둬라! 전과자들도 정치하고 약쟁이도 음악하고 방송하고 잘들사는 그런세상이다! "
inputs = tokenizer(text, return_tensor='pt', truncation=True, max_length=128, padding=True)

In [ ]:
def predict_sentiment(text):
    model.eval()
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=128,
        padding=True
    ).to(device)
    with torch.no_grad():
        outputs = model(**inputs)

    logits = outputs.logits
    probs = torch.softmax(logits, dim=-1)
    prediction = torch.argmax(probs, dim=-1).item()

    return prediction, probs[0]

In [ ]:
text

'나는 정말 불행해요'

In [ ]:
label, score = predict_sentiment(text)
print(f"label -> {label}, score -> {score}")

label -> 1, score -> tensor([0.4787, 0.5213], device='cuda:0')


In [ ]:
text = "나는 정말 행복해요"
label, score = predict_sentiment(text)
print(f"label -> {label}, score -> {score}")

label -> 1, score -> tensor([0.4812, 0.5188], device='cuda:0')
